// Lifestyle mockups. Takes a product's own storefront image, which for these stores is a
// flat print-on-demand mockup, and asks an image model to put it into a real scene, so a
// product page has something that looks photographed rather than generated by a fulfiller.
//
// Scene direction is per brand and lives in app_settings alongside cs_reply_structure, so
// it can be retuned from the UI without a deploy. DEFAULT_SCENES is only the fallback.
//
// The caveat that shapes this whole file: the model redraws the entire frame, artwork
// included, and text heavy designs come back with mangled lettering. So nothing here
// publishes on its own, nothing is stored, and every image has to be looked at before it
// goes anywhere near a live product. Attaching is a separate, deliberate call.

import { getSetting, setSetting } from './db.js';

const OPENAI_URL = 'https://api.openai.com/v1/images/edits';
// GPT Image 2.5 ships as two variants: flare for fast general generation, sunburst for
// editing precision. Preserving the artwork on a shirt that already exists is precisely
// an editing-precision job, so sunburst is the default. Override with MOCKUP_MODEL.
const MODEL = process.env.MOCKUP_MODEL || 'gpt-image-2.5-sunburst';

// gpt-image-1 defaults input_fidelity to "low", which is what made lettering come back
// redrawn, so it gets "high". The 2.5 models do not document this parameter at all and
// would reject it, hence the narrow version check at the call site rather than a loose
// /^gpt-image/ match. Check this first if fidelity regresses on a model swap.
const INPUT_FIDELITY = process.env.MOCKUP_INPUT_FIDELITY || 'high';

// The route declares maxDuration = 300. Give up just under that so a slow render comes
// back as a real message rather than a platform timeout page. Pro allows up to 800s if
// max quality at large sizes ever needs it; raise both together or this guard is moot.
const TIME_BUDGET_MS = 290000;

export const SIZES = {
  portrait: '1024x1536',
  square: '1024x1024',
  landscape: '1536x1024',
};

// Scene direction per brand, written to match the voice each brand already uses in
// brand_voices. These are starting points: edit them in the Mockups tab, which saves
// over them in app_settings.
const DEFAULT_SCENES = {
  elderemo:
    'Outside a small music venue after dark. Someone in their late twenties or thirties ' +
    'wearing the shirt, leaning against a brick wall, hands in pockets, unbothered. A ' +
    'neon sign and a couple of other people out of focus behind them. Cool night light ' +
    'with warm spill from the doorway. Candid, not posed, not smiling at the camera.',
  poppunks:
    'Warm late afternoon sun, outdoors. Someone wearing the shirt mid-laugh in the middle ' +
    'of a conversation, sitting on a low concrete ledge with a skatepark or festival ' +
    'fencing softly blurred behind them. Bright, high energy, genuinely happy, the kind of ' +
    'photo a friend takes rather than a photographer.',
  wallspoke:
    'The framed print hanging on the wall of a calm, lived-in living room. Off-white wall, ' +
    'a sideboard or sofa arm entering the bottom of the frame, a plant and a couple of ' +
    'books nearby. Soft daylight from a window to one side. Shot slightly off-square, the ' +
    'way an interiors photograph is, with the print clearly the subject.',
};

const GENERIC_SCENE =
  'A natural, well-lit everyday setting where someone would really use this product. ' +
  'Candid and photographic, with the product clearly the subject of the frame.';

// Applied on top of whatever scene is chosen. These are the rules that keep the result
// usable as a product image instead of an art piece, and they are where the fidelity
// fight is fought: the artwork instruction is repeated because one mention is not enough.
const HARD_RULES = [
  'Keep the product exactly as it appears in the supplied photo: same colours, same ' +
    'artwork, same proportions, same position of the print on the item.',
  'Do not redraw, restyle, re-letter, translate, or "improve" any text or lettering in ' +
    'the artwork. Reproduce it character for character, in the same typeface.',
  'Show the whole design. Do not crop into it, fold it out of view, or cover it.',
  'Photographic and realistic: natural light, shallow depth of field, real textures. ' +
    'Not an illustration, not a 3D render, not a collage.',
  'No added logos, watermarks, brand marks, slogans, or text anywhere in the frame.',
];

export function sceneKey(brand) {
  return 'mockup_scene_' + brand;
}

export function defaultScene(brand) {
  return DEFAULT_SCENES[brand] || GENERIC_SCENE;
}

export async function sceneFor(brand) {
  const saved = await getSetting(sceneKey(brand));
  return (saved && saved.trim()) || defaultScene(brand);
}

export async function saveScene(brand, scene) {
  const text = String(scene || '').trim();
  if (!text) throw new Error('A scene cannot be empty.');
  await setSetting(sceneKey(brand), text);
}

function buildPrompt(scene, notes) {
  const extra = String(notes || '').trim();
  return [
    'Keep the product in the supplied photo exactly as it is, and change only what surrounds it. Put it into this scene:',
    '',
    String(scene).trim(),
    '',
    ...(extra ? ['Extra direction for this shot: ' + extra, ''] : []),
    'Rules:',
    ...HARD_RULES.map((r) => '- ' + r),
  ].join('\n');
}

// One image per call, on purpose: two would not fit in the function's time budget.
// Returns { b64, size, prompt } and never touches the database or Shopify.
export async function generateMockup({ brand, imageUrl, scene, notes, size, quality }) {
  if (!process.env.OPENAI_API_KEY) {
    throw new Error('OPENAI_API_KEY is not set, so no mockups can be generated.');
  }
  if (!imageUrl) throw new Error('That product has no image to work from.');

  const src = await fetch(imageUrl);
  if (!src.ok) throw new Error('Could not fetch the product image from Shopify (' + src.status + ').');
  const bytes = Buffer.from(await src.arrayBuffer());
  const mime = src.headers.get('content-type') || 'image/png';

  const prompt = buildPrompt(scene || (await sceneFor(brand)), notes);

  const form = new FormData();
  form.append('model', MODEL);
  form.append('image', new Blob([bytes], { type: mime }), 'product.png');
  form.append('prompt', prompt);
  form.append('size', SIZES[size] || SIZES.portrait);
  form.append('quality', quality || 'medium');
  form.append('n', '1');
  if (/^gpt-image-1/.test(MODEL)) form.append('input_fidelity', INPUT_FIDELITY);

  const abort = new AbortController();
  const timer = setTimeout(() => abort.abort(), TIME_BUDGET_MS);
  let res;
  try {
    res = await fetch(OPENAI_URL, {
      method: 'POST',
      headers: { Authorization: 'Bearer ' + process.env.OPENAI_API_KEY },
      body: form,
      signal: abort.signal,
    });
  } catch (err) {
    if (err && err.name === 'AbortError') {
      throw new Error('The image took longer than the 300 second function limit. Drop the quality a notch, or raise maxDuration in the route and TIME_BUDGET_MS together.');
    }
    throw err;
  } finally {
    clearTimeout(timer);
  }

  if (!res.ok) {
    const text = await res.text();
    // Worth naming: gpt-image-1 is gated behind organisation verification, and the raw
    // 403 does not make that obvious.
    if (res.status === 403 && /verif/i.test(text)) {
      throw new Error('OpenAI has not verified this organisation for ' + MODEL + '. Verify it in the OpenAI dashboard, then try again.');
    }
    if (res.status === 400 && /model/i.test(text)) {
      throw new Error('OpenAI rejected the model "' + MODEL + '". Check the id, or set MOCKUP_MODEL to one your account can use. It said: ' + text.slice(0, 200));
    }
    if (res.status === 401) throw new Error('OpenAI rejected the API key.');
    throw new Error('Image generation failed (' + res.status + '): ' + text.slice(0, 300));
  }

  const data = await res.json();
  const b64 = data.data && data.data[0] && data.data[0].b64_json;
  if (!b64) throw new Error('The image model returned nothing usable.');

  return { b64, size: SIZES[size] || SIZES.portrait, prompt };
}
