// Lifestyle mockups. Takes a product's own storefront image, which for these stores is a
// flat print-on-demand mockup, and asks an image model to put it into a real scene, so a
// product page has something that looks photographed rather than generated by a fulfiller.
//
// Scene direction is per brand and lives in app_settings alongside cs_reply_structure, so
// it can be retuned from the UI without a deploy. DEFAULT_SCENES is only the fallback.
//
// The caveat that shapes this whole file: the model redraws the entire frame, artwork
// included, and text heavy designs come back with mangled lettering. So nothing here
// publishes on its own, nothing is stored, and every image has to be looked at before it
// goes anywhere near a live product. Attaching is a separate, deliberate call.

import Anthropic from '@anthropic-ai/sdk';
import { getSetting, setSetting, getVoiceRow } from './db.js';
import { brandVoice as fallbackVoice } from './brands.js';
import { stripDashes } from './classify.js';

const anthropic = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });
// Scene ideas are short creative writing in the brand voice, the same job as a reply
// draft, so they share DRAFT_MODEL rather than taking a variable of their own.
const SCENE_MODEL = process.env.DRAFT_MODEL || 'claude-sonnet-4-6';

const OPENAI_URL = 'https://api.openai.com/v1/images/edits';
// GPT Image 2.5 ships as two variants: flare for fast general generation, sunburst for
// editing precision. Preserving the artwork on a shirt that already exists is precisely
// an editing-precision job, so sunburst is the default. Override with MOCKUP_MODEL.
const MODEL = process.env.MOCKUP_MODEL || 'gpt-image-2.5-sunburst';

// gpt-image-1 defaults input_fidelity to "low", which is what made lettering come back
// redrawn, so it gets "high". The 2.5 models do not document this parameter at all and
// would reject it, hence the narrow version check at the call site rather than a loose
// /^gpt-image/ match. Check this first if fidelity regresses on a model swap.
const INPUT_FIDELITY = process.env.MOCKUP_INPUT_FIDELITY || 'high';

// The route declares maxDuration = 300. Give up just under that so a slow render comes
// back as a real message rather than a platform timeout page. Pro allows up to 800s if
// max quality at large sizes ever needs it; raise both together or this guard is moot.
const TIME_BUDGET_MS = 290000;

export const SIZES = {
  portrait: '1024x1536',
  square: '1024x1024',
  landscape: '1536x1024',
};

// Scene direction per brand, written to match the voice each brand already uses in
// brand_voices. These are starting points: edit them in the Mockups tab, which saves
// over them in app_settings.
const DEFAULT_SCENES = {
  elderemo:
    'Outside a small music venue after dark. Someone in their late twenties or thirties ' +
    'wearing the shirt, leaning against a brick wall, hands in pockets, unbothered. A ' +
    'neon sign and a couple of other people out of focus behind them. Cool night light ' +
    'with warm spill from the doorway. Candid, not posed, not smiling at the camera.',
  poppunks:
    'Warm late afternoon sun, outdoors. Someone wearing the shirt mid-laugh in the middle ' +
    'of a conversation, sitting on a low concrete ledge with a skatepark or festival ' +
    'fencing softly blurred behind them. Bright, high energy, genuinely happy, the kind of ' +
    'photo a friend takes rather than a photographer.',
  wallspoke:
    'The framed print hanging on the wall of a calm, lived-in living room. Off-white wall, ' +
    'a sideboard or sofa arm entering the bottom of the frame, a plant and a couple of ' +
    'books nearby. Soft daylight from a window to one side. Shot slightly off-square, the ' +
    'way an interiors photograph is, with the print clearly the subject.',
};

// Variations for a batch. Same scene every time, different person and camera, so five
// images read as five photographs from one shoot rather than five attempts at one photo.
// Relying on model nondeterminism alone gives five near-identical frames, especially with
// HARD_RULES clamping everything down, so the difference is stated explicitly.
//
// These only ever move the subject, the framing and the light. Nothing in here may touch
// the product: that is HARD_RULES' job and the two must not argue. Keyed per brand for
// the same reason the scenes are, since Wallspoke sells wall art and has no model to
// photograph.
const DEFAULT_VARIATIONS = {
  wallspoke: [
    'Straight on, centred, the print filling most of the frame.',
    'Wider, from further back, showing more of the room around it and the print off to one side.',
    'Three-quarter angle from the left, the wall receding, a nearer object soft in the foreground.',
    'Lower viewpoint looking slightly up at the print, as if from a seat in the room.',
    'Tighter crop on one corner of the frame, the texture of the paper and the wall visible.',
    'Later in the day, warmer low light raking across the wall from one side.',
  ],
};

// Apparel default: a different person and a different camera each time.
const GENERIC_VARIATIONS = [
  'Mid-shot, the person standing square to the camera, relaxed.',
  'Three-quarter angle from slightly below, a different person, caught mid-movement and looking away.',
  'Closer crop from the chest up, a different person again, background thrown further out of focus.',
  'Wider shot with more of the setting, the person off to one side of the frame and smaller in it.',
  'Side profile, candid, a second person partly in frame behind them.',
  'From behind and to one side, the person turning back towards the camera.',
];

export function variationsFor(brand, count = 1) {
  const list = DEFAULT_VARIATIONS[brand] || GENERIC_VARIATIONS;
  // Cycle rather than run out, so an unexpectedly large batch still varies.
  return Array.from({ length: Math.max(1, count) }, (_, i) => list[i % list.length]);
}

const GENERIC_SCENE =
  'A natural, well-lit everyday setting where someone would really use this product. ' +
  'Candid and photographic, with the product clearly the subject of the frame.';

// Applied on top of whatever scene is chosen. These are the rules that keep the result
// usable as a product image instead of an art piece, and they are where the fidelity
// fight is fought: the artwork instruction is repeated because one mention is not enough.
const HARD_RULES = [
  'Keep the product exactly as it appears in the supplied photo: same colours, same ' +
    'artwork, same proportions, same position of the print on the item.',
  'Do not redraw, restyle, re-letter, translate, or "improve" any text or lettering in ' +
    'the artwork. Reproduce it character for character, in the same typeface.',
  'Show the whole design. Do not crop into it, fold it out of view, or cover it.',
  'Photographic and realistic: natural light, shallow depth of field, real textures. ' +
    'Not an illustration, not a 3D render, not a collage.',
  'No added logos, watermarks, brand marks, slogans, or text anywhere in the frame.',
];

export function sceneKey(brand) {
  return 'mockup_scene_' + brand;
}

export function defaultScene(brand) {
  return DEFAULT_SCENES[brand] || GENERIC_SCENE;
}

export async function sceneFor(brand) {
  const saved = await getSetting(sceneKey(brand));
  return (saved && saved.trim()) || defaultScene(brand);
}

export async function saveScene(brand, scene) {
  const text = String(scene || '').trim();
  if (!text) throw new Error('A scene cannot be empty.');
  await setSetting(sceneKey(brand), text);
}

// "Rotate" in the tab: Claude writes a fresh scene for this product, in the brand's voice,
// steering away from the scenes already seen this session. It looks at the product image
// so the setting suits the design (a skeleton print and a floral one want different
// rooms), but it only ever writes the *surroundings*. The product itself is HARD_RULES'
// job, and a scene that described the artwork would argue with them.
//
// Returns text only. Nothing is saved: the person reads it, edits it if they like, and
// "Save as default" stays the only way a scene becomes the store's default.
export async function suggestScene({ brand, product, current, previous }) {
  if (!process.env.ANTHROPIC_API_KEY) throw new Error('ANTHROPIC_API_KEY is not set.');
  const voice = (await getVoiceRow(brand)) || fallbackVoice(brand);
  const avoid = [current, ...(previous || [])]
    .map((x) => String(x || '').trim()).filter(Boolean).slice(0, 8);

  const wallArt = brand === 'wallspoke';
  const lines = [
    'Write one new scene for a lifestyle product photo of ' +
      (product && product.title ? '"' + product.title + '"' : 'this product') +
      (product && product.productType ? ' (' + product.productType + ')' : '') + '.',
    wallArt
      ? 'It is wall art. Describe the room it hangs in and how it is photographed.'
      : 'It is apparel. Describe who is wearing it, where they are, what they are doing, and the light.',
    '',
    'Rules:',
    '- 3 to 4 sentences, in the same plain, concrete style as the examples below. A photo brief, not marketing copy.',
    '- Describe only the setting, the ' + (wallArt ? 'room' : 'person') + ', the moment and the light. Never describe the artwork, its colours or any text on it.',
    '- Pick a setting this brand\'s customers would actually be in, suited to the look of the design in the image.',
    '- Clearly different from every scene listed under "Already used": a different place, time of day and mood, not a reworded copy.',
    '- No em dashes or en dashes. No emojis, no markdown, no preamble. Reply with the scene and nothing else.',
  ];
  if (avoid.length) {
    lines.push('', 'Already used:', ...avoid.map((a, i) => (i + 1) + '. ' + a));
  }

  const content = [];
  if (product && product.image) content.push({ type: 'image', source: { type: 'url', url: product.image } });
  content.push({ type: 'text', text: lines.join('\n') });

  const res = await anthropic.messages.create({
    model: SCENE_MODEL,
    max_tokens: 400,
    system: voice + '\n\nYou are art directing lifestyle product photography for this brand.',
    messages: [{ role: 'user', content }],
  });
  const text = stripDashes(res.content.filter((b) => b.type === 'text').map((b) => b.text).join(' '));
  if (!text) throw new Error('Claude returned no scene. Try again.');
  return text;
}

function buildPrompt(scene, notes, variation) {
  const extra = String(notes || '').trim();
  const vary = String(variation || '').trim();
  return [
    'Keep the product in the supplied photo exactly as it is, and change only what surrounds it. Put it into this scene:',
    '',
    String(scene).trim(),
    '',
    // Variation before notes so a hand-typed note wins if the two ever disagree.
    ...(vary ? ['Framing and subject for this particular shot: ' + vary, ''] : []),
    ...(extra ? ['Extra direction for this shot: ' + extra, ''] : []),
    'Rules:',
    ...HARD_RULES.map((r) => '- ' + r),
  ].join('\n');
}

// One image per call, on purpose: two would not fit in the function's time budget.
// Returns { b64, size, prompt } and never touches the database or Shopify.
export async function generateMockup({ brand, imageUrl, scene, notes, size, quality, variation }) {
  if (!process.env.OPENAI_API_KEY) {
    throw new Error('OPENAI_API_KEY is not set, so no mockups can be generated.');
  }
  if (!imageUrl) throw new Error('That product has no image to work from.');

  const src = await fetch(imageUrl);
  if (!src.ok) throw new Error('Could not fetch the product image from Shopify (' + src.status + ').');
  const bytes = Buffer.from(await src.arrayBuffer());
  const mime = src.headers.get('content-type') || 'image/png';

  const prompt = buildPrompt(scene || (await sceneFor(brand)), notes, variation);

  const form = new FormData();
  form.append('model', MODEL);
  form.append('image', new Blob([bytes], { type: mime }), 'product.png');
  form.append('prompt', prompt);
  form.append('size', SIZES[size] || SIZES.portrait);
  form.append('quality', quality || 'medium');
  form.append('n', '1');
  if (/^gpt-image-1/.test(MODEL)) form.append('input_fidelity', INPUT_FIDELITY);

  const abort = new AbortController();
  const timer = setTimeout(() => abort.abort(), TIME_BUDGET_MS);
  let res;
  try {
    res = await fetch(OPENAI_URL, {
      method: 'POST',
      headers: { Authorization: 'Bearer ' + process.env.OPENAI_API_KEY },
      body: form,
      signal: abort.signal,
    });
  } catch (err) {
    if (err && err.name === 'AbortError') {
      throw new Error('The image took longer than the 300 second function limit. Drop the quality a notch, or raise maxDuration in the route and TIME_BUDGET_MS together.');
    }
    throw err;
  } finally {
    clearTimeout(timer);
  }

  if (!res.ok) {
    const text = await res.text();
    // Worth naming: gpt-image-1 is gated behind organisation verification, and the raw
    // 403 does not make that obvious.
    if (res.status === 403 && /verif/i.test(text)) {
      throw new Error('OpenAI has not verified this organisation for ' + MODEL + '. Verify it in the OpenAI dashboard, then try again.');
    }
    if (res.status === 400 && /model/i.test(text)) {
      throw new Error('OpenAI rejected the model "' + MODEL + '". Check the id, or set MOCKUP_MODEL to one your account can use. It said: ' + text.slice(0, 200));
    }
    if (res.status === 401) throw new Error('OpenAI rejected the API key.');
    throw new Error('Image generation failed (' + res.status + '): ' + text.slice(0, 300));
  }

  const data = await res.json();
  const b64 = data.data && data.data[0] && data.data[0].b64_json;
  if (!b64) throw new Error('The image model returned nothing usable.');

  return { b64, size: SIZES[size] || SIZES.portrait, prompt, variation: variation || null };
}
